# Generated by Django 5.2.7 on 2025-10-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100)),
                ('usuario', models.CharField(blank=True, default='', max_length=150)),
                ('detalle', models.TextField(blank=True, default='')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('valor', models.CharField(blank=True, default='', max_length=255)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
